namespace CadastroAniManga
{
    public enum Genero
    { 
        Action = 1,
        Adventure = 2,
        Cars = 3,
        Comedy = 4,
        Dementia = 5,
        Demons = 6,
        Mystery = 7,
        Drama = 8,
        Ecchi = 9,
        Fantasy = 10,
        Game = 11,
        Historical = 12,
        Horror = 13,
        Kids = 14,
        Magic = 15,
        MartialArts = 16,
        Mecha = 17,
        Music = 18,
        Parody = 19,
        Samurai = 20,
        Romance = 21,
        School = 22,
        SciFi = 23,
        Shoujo = 24,
        Shounen = 25,
        Space = 26,
        Sports = 27,
        SuperPower = 28,
        Vampire = 29,
        Yaoi = 30,
        Yuri = 31,
        Harem = 32,
        SliceOfLife = 33,
        Supernatural = 34,
        Military = 35,
        Police = 36,
        Psychological = 37,
        Thriller = 38,
        Seinen = 39,
        Josei = 40
    }
}